import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorial: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorial: [
    "introduction",
    "tutorial/install",
    {
      type: "category",
      label: "Usages",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "How to use DashJsonGrid",
        slug: "/category/usages",
        description:
          "Simple guides for showing the basic usages of this component.",
      },
      items: [
        "tutorial/usages/data",
        "tutorial/usages/theme",
        "tutorial/usages/search-and-select",
      ],
    },
    {
      type: "category",
      label: "Examples",
      collapsed: true,
      link: {
        type: "doc",
        id: "tutorial/examples/index",
      },
      items: ["tutorial/examples/editor"],
    },
    "license",
  ],

  apis: [
    "api-overview",
    {
      type: "category",
      label: "mixins",
      collapsed: true,
      link: {
        type: "doc",
        id: "apis/mixins/index",
      },
      items: [
        "apis/mixins/Route",
        "apis/mixins/is_sequence",
        "apis/mixins/sanitize_list_index",
        "apis/mixins/get_item_of_object",
        "apis/mixins/set_item_of_object",
        "apis/mixins/pop_item_of_object",
        "apis/mixins/MixinDataRoute",
        "apis/mixins/MixinFile",
      ],
    },
    {
      type: "category",
      label: "typehints",
      collapsed: true,
      link: {
        type: "doc",
        id: "apis/typehints/index",
      },
      items: ["apis/typehints/ThemeConfigs"],
    },
    "apis/DashJsonGrid",
  ],
};

export default sidebars;
