name: Bug report
description: Something is not working correctly.
title: "[BUG]"
labels:
  - bug
  - to be solved

body:
  - type: checkboxes
    attributes:
      label: Get started
      options:
        - label: >-
            I have read [Contributing guidelines](https://github.com/cainmagi/dash-json-grid/blob/main/CONTRIBUTING.md).
          required: true
        - label: >-
            I agree to follow the [Code of Conduct](https://github.com/cainmagi/dash-json-grid/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: >-
            I have confirmed that my issue is not duplicated with an existing issue.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: >-
        Steps to reproduce the behavior. Instead of describing the steps, you could also provide your codes related to the error here.
      value: |
        1. Get package from '...'
        2. Then run '...'
        3. An error occurs.

  - type: textarea
    attributes:
      label: Traceback
      description: >-
        The python traceback of the bug. If there is no traceback, please describe (1) The expected behaviors. (2) The actual behaviors.
      render: bash

  - type: textarea
    attributes:
      label: Behaviors
      description: >-
        If there is no traceback, please describe (1) The expected behaviors. (2) The actual behaviors.
      value: |
        1. The expected behaviors:
        2. The actual behaviors:

  - type: textarea
    attributes:
      label: Screenshots
      description: >-
        If applicable, add screenshots to help explain your problem.

  - type: input
    attributes:
      label: OS
      description: >-
        e.g. Ubuntu 24.04, Debian 12, Windows 11 23H2
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
      description: >-
        e.g. 3.13
    validations:
      required: true
  - type: input
    attributes:
      label: Dash JSON Grid Viewer version
      description: >-
        e.g. 0.x.x
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here.
