name: Docs request
description: Report a problem or a request for the docs.
title: "[Docs]"
labels:
  - documentation
  - to be solved

body:
  - type: checkboxes
    attributes:
      label: Get started
      options:
        - label: >-
            I have read [Contributing guidelines](https://github.com/cainmagi/dash-json-grid/blob/main/CONTRIBUTING.md).
          required: true
        - label: >-
            I agree to follow the [Code of Conduct](https://github.com/cainmagi/dash-json-grid/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: >-
            I have confirmed that my issue is not duplicated with an existing issue.
          required: true

  - type: textarea
    attributes:
      label: Problem
      description: >-
        If you meet any problems with the documentation, please describe your problems here.

  - type: textarea
    attributes:
      label: Required feature
      description: >-
        If you need more explanations in the documentation, please describe your needs here.

  - type: input
    attributes:
      label: Dash JSON Grid Viewer version
      description: >-
        e.g. 0.x.x
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here.
