name: Vulnerability report
description: Report a vulnerability.
title: "[VUL]"
labels:
  - vulnerability
  - to be solved

body:
  - type: checkboxes
    attributes:
      label: Get started
      options:
        - label: >-
            I have read [Contributing guidelines](https://github.com/cainmagi/dash-json-grid/blob/main/CONTRIBUTING.md).
          required: true
        - label: >-
            I agree to follow the [Code of Conduct](https://github.com/cainmagi/dash-json-grid/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: >-
            I have reviewed the [Security Policy](https://github.com/cainmagi/dash-json-grid/blob/main/SECURITY.md).
          required: true
        - label: >-
            I have confirmed that my issue is not duplicated with an existing issue.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: >-
        A clear and concise description of the vulnerability.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Dependencies
      description: >-
        If applicable, put the list of dependencies that are related to this vulnerability, including the versions that the dependencies suppose to be updated.

  - type: input
    attributes:
      label: OS
      description: >-
        e.g. Ubuntu 24.04, Debian 12, Windows 11 23H2
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
      description: >-
        e.g. 3.13
    validations:
      required: true
  - type: input
    attributes:
      label: Dash JSON Grid Viewer version
      description: >-
        e.g. 0.3.3
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here.
