name: Test deployment

on:
  pull_request:
    branches:
      - docs
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - name: Enable Corepack and Yarn
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare yarn --activate

      - name: Install dependencies
        run: yarn install --immutable
      - name: Test build website
        run: yarn build
